apiVersion: v1
kind: PersistentVolume
metadata:
 name: demo
spec:
 capacity:
   storage: 1Gi
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Recycle
 nfs:
   path: /opt/data/vol/0
   server: 192.168.23.159