apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
  labels:
    app: mongo
    version: v1
spec:
  ports:
  - name: port
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongo
    version: v1
  type: ClusterIP
  sessionAffinity: None
