apiVersion: v1
kind: Service
metadata:
  name: myemp
  labels:
    app: myemp
    version: v1
spec:
  ports:
  - name: port
    protocol: TCP
    port: 80
    targetPort: 8888
  selector:
    app: myemp
    version: v1
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster