apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: myapp
    tier: data
spec:
  containers:
    - name: mysql
      image: mysql
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: password 
      ports:
       - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: myapp
    tier: data
spec:
  ports:
    - port: 3306
      name: mysql
      targetPort: 3306
      protocol: TCP
  selector:
    app: myapp
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-external
  labels:
    app: myapp
    tier: data
spec:
  type: NodePort
  ports:
    - port: 3306
      name: mysql-ext
      targetPort: 3306
      protocol: TCP
  selector:
    app: myapp


