apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    #app: todoapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: janakiramm/todo-app
        name: web
        ports:
        - containerPort: 3000  