apiVersion: "v1"
kind: Pod
metadata:
  name: my-pod
  labels:
    env: web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - containerPort: 80
          name: http-server
          protocol: TCP
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim: 
        claimName: my-pvc 